//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdonnancementsEquitables.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrdonnancementsEquitables.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;job_type&quot;: &quot;JobP&quot;,
        ///  &quot;job_list&quot;: [
        ///    {
        ///      &quot;time&quot;: 1,
        ///      &quot;deadline&quot;: 12,
        ///      &quot;profit&quot;: 4
        ///    },
        ///    {
        ///      &quot;time&quot;: 1,
        ///      &quot;deadline&quot;: 10,
        ///      &quot;profit&quot;: 3
        ///    },
        ///    {
        ///      &quot;time&quot;: 1,
        ///      &quot;deadline&quot;: 8,
        ///      &quot;profit&quot;: 1
        ///    },
        ///    {
        ///      &quot;time&quot;: 1,
        ///      &quot;deadline&quot;: 7,
        ///      &quot;profit&quot;: 6
        ///    },
        ///    {
        ///      &quot;time&quot;: 1,
        ///      &quot;deadline&quot;: 6,
        ///      &quot;profit&quot;: 1
        ///    },
        ///    {
        ///      &quot;time&quot;: 1,
        ///      &quot;deadline&quot;: 5,
        ///      &quot;profit&quot;: 6
        ///    },
        ///    {
        ///      &quot;time&quot;: 1, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GloutonParProfits {
            get {
                return ResourceManager.GetString("GloutonParProfits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;job_type&quot;: &quot;Job&quot;,
        ///  &quot;job_list&quot;: [
        ///    {
        ///      &quot;time&quot;: 6,
        ///      &quot;deadline&quot;: 8
        ///    },
        ///    {
        ///      &quot;time&quot;: 4,
        ///      &quot;deadline&quot;: 9
        ///    },
        ///    {
        ///      &quot;time&quot;: 7,
        ///      &quot;deadline&quot;: 15
        ///    },
        ///    {
        ///      &quot;time&quot;: 8,
        ///      &quot;deadline&quot;: 20
        ///    },
        ///    {
        ///      &quot;time&quot;: 3,
        ///      &quot;deadline&quot;: 21
        ///    },
        ///    {
        ///      &quot;time&quot;: 5,
        ///      &quot;deadline&quot;: 22
        ///    }
        ///  ]
        ///}.
        /// </summary>
        public static string Hogdson {
            get {
                return ResourceManager.GetString("Hogdson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
